# create_pod_netologyweb.yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netology-web
  name: netology-web
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    name: echoserver